#
# Basic Dockerfile for lusee-night/luuseepy, to establish
# baseline testing before adding test elements to CI.
# 
# This file is to be referenced when building the luseepy
# images from a folder one level above. Example:
#
# sudo docker build -f docker/Dockerfile -t lusee:0.1 .
# 

FROM python:3.10.1-bullseye

WORKDIR /app

COPY docker/requirements.txt requirements.txt
RUN pip install -r requirements.txt
RUN pip install jupyterlab

COPY lusee lusee
COPY tests tests
COPY notebooks notebooks/

CMD ["python"]
