# Note a copy of the local "astropy cache" into the image
# This is the difference between this and "non-legacy" file.

FROM lusee/lusee-night-refspec-cppyy:1.0

ARG reqs=requirements-unity-luseepy.txt

ADD .astropy /root/.astropy

WORKDIR /data

WORKDIR /user/luseepy

COPY docker/${reqs} requirements.txt
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
#
# Important:
RUN pip install jupyterlab
#
RUN rm requirements.txt
#
COPY lusee lusee
COPY tests tests
#
ENV REFSPEC_PATH=/user/refspec
ENV PYTHONPATH=/user/luseepy:$PYTHONPATH
ENV LUSEE_DRIVE_DIR=/data/
#
CMD ["bash"]
