#
# Lusee-night Dockerfile for CI.
# 
# This file is to be referenced when building the luseepy
# images from a folder one level above. Example:
#
# sudo docker build -f docker/Dockerfile -t lusee-ci:0.1 .
# 

FROM python:3.10.1-bullseye

COPY docker/requirements.txt requirements.txt
RUN pip install -r requirements.txt

CMD ["python"]
