# DEPRECATED
#
# Basic Dockerfile used to build a Debian image
# containing the packages required by lusee-night/luseepy.
# 
# This file is to be referenced when building the luseepy
# images from a folder one level above. Example:
#
# sudo docker build -f docker/Dockerfile-myfile -t MYTAGNAME .
#

FROM python:3.10.1-bullseye

WORKDIR /app

# Apparently required by "fitsio"
RUN apt-get install libbz2-dev

# We may have a few versions of requirements,
# hence a few custom names, to simplify experiments

COPY docker/requirements_fresh.txt requirements.txt
RUN pip install -r requirements.txt

ADD .astropy /root/.astropy

WORKDIR /user

