##### USED PRIMARILY TO BUILD THE "UNITY FOUNDATION" IMAGE
#
# 
# Note a copy of the "astropy cache"

FROM lusee/lusee-night-refspec-cppyy:0.1

ARG reqs=requirements-foundation.txt

ADD .astropy /root/.astropy

WORKDIR /data

WORKDIR /user/luseepy

COPY docker/${reqs} requirements.txt
RUN pip install -r requirements.txt
# Important:
RUN pip install jupyterlab
#
RUN rm requirements.txt
#
COPY lusee lusee
COPY tests tests
#
ENV PYTHONPATH=/user/luseepy:/user/refspec/cppyy
ENV LUSEE_DRIVE_DIR=/data

CMD ["bash"]
