# Note that we force generationof the "astropy cache"

FROM lusee/lusee-night-refspec-cppyy:1.0

ARG reqs=requirements-unity-luseepy.txt

WORKDIR /data

WORKDIR /user/luseepy

COPY docker/${reqs} requirements.txt
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# force astropy to create /root/.astropy directory
RUN python -c "import astropy.coordinates, astropy.time; astropy.coordinates.get_body('moon',astropy.time.Time('2026-01-01'))" && ls -l /root/.astropy

#
# Important:
RUN pip install jupyterlab
#
RUN rm requirements.txt
#
COPY lusee lusee
COPY tests tests
#
ENV REFSPEC_PATH=/user/refspec
ENV LUSEEPY_PATH=/user/luseepy
ENV PYTHONPATH=$LUSEEPY_PATH:$PYTHONPATH
ENV LUSEE_DRIVE_DIR=/data/
#
CMD ["bash"]
