# Adding "pyshtools" on top of base
# Includes Jupyter

FROM lusee/lusee-night-base:0.1

WORKDIR /app


COPY docker/requirements-jupyter.txt requirements-jupyter.txt
RUN pip install -r requirements-jupyter.txt

# Application-level component:
COPY simulation simulation

RUN rm requirements-jupyter.txt


# We'll be writing out data and it's best
# to have a mount point we can map to a folder
# on the host machine. This is also important
# for Singularuty.

WORKDIR /output
