# Adding "pyshtools" on top of base
# Includes Jupyter

FROM lusee/lusee-night-base:0.1
WORKDIR /app
COPY docker/requirements-jupyter.txt requirements-jupyter.txt
RUN pip install -r requirements-jupyter.txt

RUN rm requirements-jupyter.txt
