#
# Basic Dockerfile used to build a Debian image
# containing the packages required by lusee-night/luseepy.
# 
# This file is to be referenced when building the luseepy
# images from a folder one level above. Example:
#
# sudo docker build -f docker/Dockerfile-base -t MYTAGNAME .
#
# Example of a tag name --
# buddhasystem/lusee-night-luseepy-base:0.1
# 

FROM python:3.10.1-bullseye

WORKDIR /app

COPY docker/requirements.txt requirements.txt
RUN pip install -r requirements.txt

WORKDIR /user

CMD ["python"]
