#
# Adding layers to the "foundation" image
#
# -----
# ARES is not pip-installable
# This will clone the master but won't be necessarily reproducible:
# RUN git clone https://github.com/mirochaj/ares.git && cd ares && python setup.py install
#
# So we are using "ARG" to define its tag, download and set it up

FROM buddhasystem/lusee-night-foundation:0.1
ARG ARES_TAG=0.7

WORKDIR /app
RUN wget https://github.com/mirochaj/ares/archive/refs/tags/v${ARES_TAG}.zip && unzip v${ARES_TAG}.zip && cd ares-${ARES_TAG} && python setup.py install

ENV PYTHONPATH "/app/ares-${ARES_TAG}"

RUN rm *.zip

WORKDIR /user

