paths:
  lusee_drive_dir: $LUSEE_DRIVE_DIR
  beam_dir: Simulations/BeamModels/LanderRegolithComparison/eight_layer_regolith
  output_dir: $LUSEE_OUTPUT_DIR

beam_config:
  type: Gaussian          # no FITS needed for the example

beams:
  N: {altitude: 90.0, azimuth: 0, sigma: 20}
  E: {altitude: 90.0, azimuth: 0, sigma: 20, angle: 90}
  S: {altitude: 90.0, azimuth: 0, sigma: 20, angle: 180}
  W: {altitude: 90.0, azimuth: 0, sigma: 20, angle: 270}

satellite:
  # Orbital parameters (defaults match lusee.Satellite defaults)
  waveform: default  # default or alt

observation:
  lunar_day: 2501
  dt: 600                 # seconds
  long: 182.258
  lat: -23.814

simulation:
  output: calibrator_sim.fits
